#GET https://localhost:7018/WeatherForecast/GetSecureWeather?token=12345
GET https://localhost:7018/WeatherForecast/GetSecureWeather
#apiKey: 12345
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcjEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBcGlVc2VyIiwiZXhwIjoxNjc5OTkyMzcyLCJpc3MiOiJraW5nZGF2aWRjb25zdWx0aW5nLmNvbSIsImF1ZCI6ImFwaSJ9.bV68URYJq50Mc_liodbHgUtkfllJ_iaZApriGauQtfY